spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/intern_demo
spring.datasource.username=postgres
spring.datasource.password=tnt22873
spring.jpa.hibernate.ddl-auto=update